version: '3.7'
services:
  json-server:
    image: 'vimagick/json-server'
    command: -H 0.0.0.0 -p 3000 -w db.json
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /app/mockapi/data:/data
    ports:
      - 13004:3000
    deploy:
      resources:
        limits:
          memory: 250M
    networks:
      - jsonserver_nw   
networks:
   jsonserver_nw: 
    driver : bridge   
