version: '3.7'

services:
  reverse:
    image: nginx
    hostname: nginx.at.internal
    volumes:
      - '/docker/nginx/conf.d:/etc/nginx/conf.d'
      - '/docker/nginx/data/certs:/etc/nginx/certs'
      - '/docker/nginx/logs:/var/log/nginx'  
      - '/docker/nginx/nginx.conf:/etc/nginx/nginx.conf'
      - '/docker/nginx/tcpconf.d/:/etc/nginx/tcpconf.d'
    command: [nginx-debug, '-g', 'daemon off;']
    ports:
      - '80:80'
      - '443:443'
      - '18000:12500'
      - '17000:12000'  
      - '11000:11000'  
