key : QUtJQVVYRlRGM1VUSFY3NSTFoK
sceret_key: NFdrQ0VydU1OWkNZU3JhUEhraVNmZ3hhWWaUkwbVRNajQvNlNNMgo=
publi_ip: My42LjI1My4xMjE=
ec2_instance: aS0wOTllNTkwZGMzZTU3Mjg1NQ==
ec2_instance-2: MDEyNjE3MTY3NzQ1ZmYyYjY=