version: '3.3'
services:
  db:
    image: mysql:8.0.18
    restart: always
    environment:
      #MYSQL_DATABASE: 'db'
      # So you don't have to use root, but you can if you like
      #MYSQL_USER: 'user'
      # You can use whatever password you like
      #MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '13007:3306'
      # Where our data will be persisted
    volumes:
      - /docker/mysql/mysql_vol:/var/lib/mysql
# Names our volume
volumes:
  my-db:
