global:
  scrape_interval:     40s
  evaluation_interval: 40s
  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      monitor: 'docker-host-alpha'

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
  - "alert.rules"

# A scrape configuration containing exactly one endpoint to scrape.
scrape_configs:
  - job_name: 'nodeexporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['nodeexporter:9100']

  - job_name: 'QA-3-nodeexporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['10.0.1.114:9100']

  - job_name: 'QA-2-nodeexporter'
    scrape_interval: 30s
    static_configs:
      - targets: ['10.0.1.64:9100']

  - job_name: 'QA-1-nodeexporter'
    scrape_interval: 30s
    static_configs:
      - targets: ['10.0.1.211:9100']

  - job_name: 'cadvisor'
    scrape_interval: 5s
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'QA-3-cadvisor'
    scrape_interval: 5s
    static_configs:
      - targets: ['10.0.1.114:8080']

  - job_name: 'QA-2-cadvisor'
    scrape_interval: 5s
    static_configs:
      - targets: ['10.0.1.64:9080']

  - job_name: 'QA-1-cadvisor'
    scrape_interval: 5s
    static_configs:
      - targets: ['10.0.1.211:9080'] 

  - job_name: 'prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'pushgateway'
    scrape_interval: 10s
    honor_labels: true
    static_configs:
      - targets: ['pushgateway:9091']


#alerting:
#  alertmanagers:
#  - scheme: http
#    static_configs:
#    - targets: 
#      - 'alertmanager:9093'

#  - job_name: 'nginx'
#    scrape_interval: 10s
#    static_configs:
#      - targets: ['10.0.1.64:80']

#  - job_name: 'aspnetcore'
#    scrape_interval: 10s
#    static_configs:
#      - targets: ['eventlog-proxy:5000', 'eventlog:5000']
